### ISSUE TITLE
Implement Portfolio Page

### ISSUE THREAD

**Issue by Stanley1312** [Stanley1312/base-web-development#1]
## Portfolio Page

**Todo:**

- [ ]  Portfolio mockup design 
- [ ]  Task break down
- [ ]  Estimate working time
